
export const Emp=[
  {
    full_name:'Maksat',
    year:'6',
    img:'https://seekflag.com/app/uploads/2021/12/Flag-of-kyrgyzstan-01.png',
    from:'kyrgyz',
    status:"Empl",
    click:'kyrgyz'
   },
    {
     full_name:'Erbol',
     year:'13',
     img:'https://seekflag.com/app/uploads/2021/12/Flag-of-kyrgyzstan-01.png',
     from:'kyrgyz',
     status:"Empl",
     click:'kyrgyz'
    },
    {
      full_name:'modric',
      year:'18',
      img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQluNssnFZPm25FLFtcBp9HtRfjBQ7TlxAjPCvyxCTe2FEdk745I5VBcVxgUx4a8qe22cU&usqp=CAU',
      from:'America',
      status:"Empl",
      click2:"from"
     },
    {
      full_name:'Argen',
      year:'15',
      img:'https://seekflag.com/app/uploads/2021/12/Flag-of-kyrgyzstan-01.png',
      from:'kyrgyz',
      status:"Empl",
      click:'kyrgyz'
     },
  
     {
      full_name:'Eminem',
      year:'13',
      img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOPqrIocLhXesopH2KmIBIDzsvGgalJfgN7w&usqp=CAU',
      from:'Brazil',
      status:"Empl",
      click2:"from"
     },

     {
      full_name:'Kaka',
      year:'21',
      img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQluNssnFZPm25FLFtcBp9HtRfjBQ7TlxAjPCvyxCTe2FEdk745I5VBcVxgUx4a8qe22cU&usqp=CAU',
      from:'America',
      status:"men",
      click2:"from"
     },
    {
     full_name:'ronaldo',
     year:'23',
     img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQluNssnFZPm25FLFtcBp9HtRfjBQ7TlxAjPCvyxCTe2FEdk745I5VBcVxgUx4a8qe22cU&usqp=CAU',
     from:'America',
     status:"men",
     click2:"from"
    },
    {
      full_name:'Jonny',
      year:'19',
      img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOPqrIocLhXesopH2KmIBIDzsvGgalJfgN7w&usqp=CAU',
      from:'Brazil',
      status:"men",
      click2:"from"
     },
     {
      full_name:'Kutman',
      year:'22',
      img:'https://seekflag.com/app/uploads/2021/12/Flag-of-kyrgyzstan-01.png',
      from:'kyrgyz',
      status:"men",
      click:'kyrgyz'
     },
      {
        full_name:'Frank',
        year:'36',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOPqrIocLhXesopH2KmIBIDzsvGgalJfgN7w&usqp=CAU',
        from:'Brazil',
        status:"women",
        click2:"from"
       },
       {
        full_name:'Brain',
        year:'51',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOPqrIocLhXesopH2KmIBIDzsvGgalJfgN7w&usqp=CAU',
        from:'Brazil',
        status:"women", 
        click2:"from"
       },
       {
        full_name:'kante',
        year:'30',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQluNssnFZPm25FLFtcBp9HtRfjBQ7TlxAjPCvyxCTe2FEdk745I5VBcVxgUx4a8qe22cU&usqp=CAU',
        from:'America',
        status:"women",
        click2:"from"
       },
       {
       full_name:'Adil',
       year:'32',
       img:'https://seekflag.com/app/uploads/2021/12/Flag-of-kyrgyzstan-01.png',
       from:'kyrgyz',
       status:"women",
       click:'kyrgyz'
      },
       
 ];
